config/routes.rb
Party::Application.routes.draw do

  get "home/home"

	resources :hosts
	resources :guests
	resources :partyms
	resources :sessions, :only => [:new, :create, :destroy]
	
  root :to => 'home#home' 

match '/home' => 'home#home' 
match 'home' => 'home#home' 
match '/signup' => 'hosts#new'
match '/signin' => 'sessions#new'
match '/signout' => 'sessions#destroy'
match 'hosts/show' => 'hosts#show'
match '/hosts' => 'hosts#index'

post "hosts/create"
put "hosts/update" 
delete "hosts/destroy"

 

	
  

  
  get "parties/index"
	 get "parties/show"
	 get "parties/new"
	 get "parties/edit"

  
	
	
	get "guests/index"
  
	get "guests/show"

	get "guests/new"

	post "guests/create"

	get "guests/edit"

	put "guests/update"
  
	delete "guests/destroy"

 
  

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	email_regex = /[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i
	
	attr_accessible :name, :email, :expected_attendees, :actual_attendees
	validates :name, :presence => true
				     :length => { :maximum => 50 }
	validates :email, :presence => true
					  :format => { :with => email_regex} 
					  :uniqueness => { :case_sensitive => false } 	
end

app/models/host.rb
require 'digest'
class Host < ActiveRecord::Base
	email_regex = /[\w+\-.]+@[a-z\d\-.]+\.[a-z]+/i
	attr_accessor :password
	attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
	validates :first_name, :presence => true,
						   :length => { :maximum => 50 }
	validates :last_name, :presence => true,
					      :length => { :maximum => 50 }
	validates :email, :presence => true,
					  :format => { :with => email_regex}, 
					  :uniqueness => { :case_sensitive => false } 
	validates :password, :presence => true,
					     :confirmation => true, 
					     :length => { :within => 6..40 }
	
	before_save :encrypt_password						

	def has_password?(submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
		host = find_by_email(email)
		return nil if host.nil?
		return host if host.has_password?(submitted_password)
	end	

	def self.authenticate_with_salt(id, cookie_salt)
		host = find_by_id(id)
		(host && host.salt == cookie_salt) ? host : nil
	end	

    private
	
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(self.password)
		end

		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end
	
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end
		
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
end	

app/models/partym.rb
class Partym < ActiveRecord::Base
	attr_accessible :name, :date, :location, :start_time, :end_time, :description, :rsvp_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
   include SessionsHelper
  end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  
   def index
  end

  def show
  end
  
  def new
  end
  
  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
 @home = "Home"
	end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
	before_filter :authenticate, :only => [:index, :edit, :update]
	before_filter :correct_host, :only => [:edit, :update]
	before_filter :admin_host, :only => [:destroy]

  def index
	@title = "All Hosts"
	@hosts = Host.paginate(:page => params[:page])
  end
	
  def show
  @host = Host.find(params[:id])
  @title = @host.first_name
  end
  
  def new
  @host = Host.new
   @title = "Sign Up"
  end
  
  def create
	@host = Host.new(params[:host])
	if @host.save
		sign_in @host
		flash[:success] = "Welcome to the Party Manager!"
		redirect_to @host
	else 
	@title = "Sign Up"
	render 'new'
    end
  end
  
  private
  
  def authenticate
	deny_access unless signed_in?
  end
  
  def correct_host
	@host = Host.find(params[:id])
	redirect_to(root_path) unless current_host?(@host)
  end	
   
  def edit
  @title = "Edit Host"
  end
  
  def update
	@host = Host.find(params[:id])
	if @host.update_attributes(params[:host])
		flash[:success] = "Profile updated."
		redirect_to @host
	else
		@title = 'Edit host'
		render = 'edit'
	end
   end	
 
  
  def destroy
	Host.find(params[:id]).destroy
	flash[:success] = "Host Annihilated"
	redirect_to hosts_path
  end

  def admin_host
	redirect_to(root_path) unless current_host.admin?
  end
  
 end
 

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def index
	@title = "Index"
  end

  def show
	@title = "Show" 
  end
  
  def new
  @title = "New"
  end
  
  def create
  end
  
  def edit
  @title = "Edit"
  end
  
  def update
  end
  
  def destroy
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  @title = "Sign In"
  end
  
  def create
	host = Host.authenticate(params[:session][:email], params[:session][:password])
	
	if host.nil?
		flash.now[:error] = "Invalid email/password combination."
		@title = "Sign in"
		render 'new'
	else
		sign_in host
		redirect_back_or host
	end
  end
  
  def destroy
	sign_out
	redirect_to '/home'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def title
		base_title = "Party Manager"
			if @title.nil?
			base_title
			else
			"#{base_title} | #{@title}"
		end
	end
	
	def gravatar_for email, options = {}
    options = {:alt => 'avatar', :class => 'avatar', :size => 80}.merge! options
    id = Digest::MD5::hexdigest email.strip.downcase
    url = 'http://www.gravatar.com/avatar/' + id + '.jpg?s=' + options[:size].to_s
    options.delete :size
    image_tag url, options
	end

end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/host_helper.rb
module HostHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(host)
		cookies.permanent.signed[:remember_token] = [host.id, host.salt]
		self.current_host = host
	end	
	
	def current_host=(host)
		@current_host = host
	end	
	
	def current_host
		@current_host ||= host_from_remember_token
	end
	
	def signed_in?
		!current_host.nil?
	end	
	
	def sign_out
		cookies.delete(:remember_token)
		self.current_host = nil
	end
	
	private

	def host_from_remember_token
		Host.authenticate_with_salt(*remember_token)
	end

	def remember_token
		cookies.signed[:remember_token] || [nil, nil]
	end
	
	def deny_access
		redirect_to signin_path, :notice => 'Please sign in to access this page'
	end
	
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end	
	
	def current_host?(host)
		host == current_host
	end	
	
	def store_location
		session[:return_to] = request.fullpath
	end
	
	def clear_return_to
		session[:return_to] = nil
	end	
	
end

app/views/guests/new.html.erb
<h1>Guests#new</h1>
<p>Find me in app/views/guests/new.html.erb</p>

app/views/home/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style type="text/css">
<!--
body {
	font: 100%/1.4 Verdana, Arial, Helvetica, sans-serif;
	background: #4E5869;
	margin: 0;
	padding: 0;
	color: #000;
}

/* ~~ Element/tag selectors ~~ */
ul, ol, dl { /* Due to variations between browsers, it's best practices to zero padding and margin on lists. For consistency, you can either specify the amounts you want here, or on the list items (LI, DT, DD) they contain. Remember that what you do here will cascade to the .nav list unless you write a more specific selector. */
	padding: 0;
	margin: 0;
}
h1, h2, h3, h4, h5, h6, p {
	margin-top: 0;	 /* removing the top margin gets around an issue where margins can escape from their containing div. The remaining bottom margin will hold it away from any elements that follow. */
	padding-right: 15px;
	padding-left: 15px; /* adding the padding to the sides of the elements within the divs, instead of the divs themselves, gets rid of any box model math. A nested div with side padding can also be used as an alternate method. */
}
a img { /* this selector removes the default blue border displayed in some browsers around an image when it is surrounded by a link */
	border: none;
}

/* ~~ Styling for your site's links must remain in this order - including the group of selectors that create the hover effect. ~~ */
a:link {
	color:#414958;
	text-decoration: underline; /* unless you style your links to look extremely unique, it's best to provide underlines for quick visual identification */
}
a:visited {
	color: #4E5869;
	text-decoration: underline;
}
a:hover, a:active, a:focus { /* this group of selectors will give a keyboard navigator the same hover experience as the person using a mouse. */
	text-decoration: none;
}

/* ~~ this container surrounds all other divs giving them their percentage-based width ~~ */
.container {
	width: 80%;
	max-width: 1260px;/* a max-width may be desirable to keep this layout from getting too wide on a large monitor. This keeps line length more readable. IE6 does not respect this declaration. */
	min-width: 780px;/* a min-width may be desirable to keep this layout from getting too narrow. This keeps line length more readable in the side columns. IE6 does not respect this declaration. */
	background: #FFF;
	margin: 0 auto; /* the auto value on the sides, coupled with the width, centers the layout. It is not needed if you set the .container's width to 100%. */
}

/* ~~ the header is not given a width. It will extend the full width of your layout. It contains an image placeholder that should be replaced with your own linked logo ~~ */
.header {
	background: #6F7D94;
}

/* ~~ These are the columns for the layout. ~~ 

1) Padding is only placed on the top and/or bottom of the divs. The elements within these divs have padding on their sides. This saves you from any "box model math". Keep in mind, if you add any side padding or border to the div itself, it will be added to the width you define to create the *total* width. You may also choose to remove the padding on the element in the div and place a second div within it with no width and the padding necessary for your design.

2) No margin has been given to the columns since they are all floated. If you must add margin, avoid placing it on the side you're floating toward (for example: a right margin on a div set to float right). Many times, padding can be used instead. For divs where this rule must be broken, you should add a "display:inline" declaration to the div's rule to tame a bug where some versions of Internet Explorer double the margin.

3) Since classes can be used multiple times in a document (and an element can also have multiple classes applied), the columns have been assigned class names instead of IDs. For example, two sidebar divs could be stacked if necessary. These can very easily be changed to IDs if that's your preference, as long as you'll only be using them once per document.

4) If you prefer your nav on the right instead of the left, simply float these columns the opposite direction (all right instead of all left) and they'll render in reverse order. There's no need to move the divs around in the HTML source.

*/
.sidebar1 {
	float: left;
	width: 20%;
	background: #93A5C4;
	padding-bottom: 10px;
}
.content {
	padding: 10px 0;
	width: 80%;
	float: left;
}

/* ~~ This grouped selector gives the lists in the .content area space ~~ */
.content ul, .content ol { 
	padding: 0 15px 15px 40px; /* this padding mirrors the right padding in the headings and paragraph rule above. Padding was placed on the bottom for space between other elements on the lists and on the left to create the indention. These may be adjusted as you wish. */
}

/* ~~ The navigation list styles (can be removed if you choose to use a premade flyout menu like Spry) ~~ */
ul.nav {
	list-style: none; /* this removes the list marker */
	border-top: 1px solid #666; /* this creates the top border for the links - all others are placed using a bottom border on the LI */
	margin-bottom: 15px; /* this creates the space between the navigation on the content below */
}
ul.nav li {
	border-bottom: 1px solid #666; /* this creates the button separation */
}
ul.nav a, ul.nav a:visited { /* grouping these selectors makes sure that your links retain their button look even after being visited */
	padding: 5px 5px 5px 15px;
	display: block; /* this gives the link block properties causing it to fill the whole LI containing it. This causes the entire area to react to a mouse click. */
	text-decoration: none;
	background: #8090AB;
	color: #000;
}
ul.nav a:hover, ul.nav a:active, ul.nav a:focus { /* this changes the background and text color for both mouse and keyboard navigators */
	background: #6F7D94;
	color: #FFF;
}

/* ~~ The footer ~~ */
.footer {
	padding: 10px 0;
	background: #6F7D94;
	position: relative;/* this gives IE6 hasLayout to properly clear */
	clear: both; /* this clear property forces the .container to understand where the columns end and contain them */
}

/* ~~ miscellaneous float/clear classes ~~ */
.fltrt {  /* this class can be used to float an element right in your page. The floated element must precede the element it should be next to on the page. */
	float: right;
	margin-left: 8px;
}
.fltlft { /* this class can be used to float an element left in your page. The floated element must precede the element it should be next to on the page. */
	float: left;
	margin-right: 8px;
}
.clearfloat { /* this class can be placed on a <br /> or empty div as the final element following the last floated div (within the #container) if the #footer is removed or taken out of the #container */
	clear:both;
	height:0;
	font-size: 1px;
	line-height: 0px;
}
-->
</style><!--[if lte IE 7]>
<style>
.content { margin-right: -1px; } /* this 1px negative margin can be placed on any of the columns in this layout with the same corrective effect. */
ul.nav a { zoom: 1; }  /* the zoom property gives IE the hasLayout trigger it needs to correct extra whiltespace between the links */
</style>
<![endif]--></head>

<body>

<div class="container">
  <div class="header">
    <!-- end .header --><%= image_tag("party.gif", :alt => "party feed") %> </div>
  <div class="sidebar1">
   
  
    <ul class="nav">

      <li><a href="#"></a></li>
    </ul>
    <p> </p>
    <p></p>
  <!-- end .sidebar1 --></div>
  <div class="content">
    <h1>WELCOME TO PARTY MANAGER</h1>
    <p></a>.</p>
    <h2>&nbsp;</h2>
    <!-- end .content --></div>
  <div class="footer">
    <p></p>
    <!-- end .footer --></div>
  <!-- end .container --></div>
</body>
</html>

app/views/hosts/_host.html.erb
<li>
	<%= link_to host.first_name, host %>
	
</li>

app/views/hosts/edit.html.erb
<h1>Edit Host</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@host) do |f| %>
			<%= render 'partials/error_messages', :object => f.object %>
			
			<%= f.label :first_name %>
			<%= f.text_field :first_name %>
			
			<%= f.label :last_name %>
			<%= f.text_field :last_name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
				
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Save Changes", :class => "btn btn-large btn-primary" %>
		<% end %>		
	</div>
</div>	



app/views/hosts/home.html.erb
<header> Welcome To Party Manager </header?

app/views/hosts/index.html.erb
<h1>All hosts</h1>

<%= will_paginate %>

<ul class ="hosts">
		<%= render @hosts %>
</ul>	
<%= will_paginate %>

app/views/hosts/new.html.erb
<h1>Sign up</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@host) do |f| %>
			<%= render 'partials/error_messages', :object => f.object %>
			<%= f.label :first_name %>
			<%= f.text_field :first_name %>
			
			<%= f.label :last_name %>
			<%= f.text_field :last_name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>
				
			<%= f.label :password %>
			<%= f.password_field :password %>
			
			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>
			
			<%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>	

app/views/hosts/show.html.erb
<div class="row">
	<aside class="span4">
		section
			<h1>
				<%= gravatar_image_tag @host.email %>
				<%= @host.first_name %><%= @host.last_name %>&nbsp<%= @host.email %>
			</h1>
		</section>
	</aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5/js"></script>
		<![endif]-->
	</head>
	<body>
		<%= render 'partials/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<div class="center hero-unit">
			<%= yield %>
			<%= render 'partials/footer' %>
		</div>
		<%= debug(params) if Rails.env.development? %>
	</body>
</html>	

app/views/partials/_error_messages.html.erb
<% if @host.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@host.errors.count, "error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
			from being saved:</h2>
		<p> There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>	
		

app/views/partials/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://www.facebook.com/schaxz/">Creator</a>
		 Srinjoy Chakravarty
	</small>
	<nav>
		<ul>
			<li><a href="http://twitter.com/#!/Srinjoy_Chakrav/">Owner</a></li>
		</ul>
	</nav>	
</footer>

app/views/partials/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul clas="nav pull-right">  
					<li><%= link_to "Home", root_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Hosts", '/hosts' %> </li>
						<li><%= link_to "Profile", current_host %> </li>
						<li><%= link_to "Settings", edit_host_path(current_host) %> </li>
					<% end %>
					<% if signed_in? %>
						<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %>
					<% end %>
				</ul>
			</nav>	
		</div>
	</div>
</header>

app/views/parties/index.html.erb
<h1>Parties#index</h1>
<p>Find me in app/views/parties/index.html.erb</p>

app/views/parties/new.html.erb
<h1>Parties#new</h1>
<p>Find me in app/views/parties/new.html.erb</p>

app/views/parties/show.html.erb
<h1>Parties#show</h1>
<p>Find me in app/views/parties/show.html.erb</p>

app/views/parties/update.html.erb
<h1>Parties#update</h1>
<p>Find me in app/views/parties/update.html.erb</p>